# Generated by Django 4.2.2 on 2023-06-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Auth_email',
            new_name='auth_email',
        ),
    ]
