# Generated by Django 4.2.2 on 2023-06-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_auth_email_book_auth_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Auth_email',
            new_name='Authemail',
        ),
    ]
