# Generated by Django 4.2.2 on 2023-06-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_auth_email_book_authemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Authemail',
            new_name='Auth_email',
        ),
    ]
